version: "3.7"

services:

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD: vrautorizador